//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.MantenimientoIdealease.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Amnl
    {
        public int Id { get; set; }
        public int IdTabla { get; set; }
        public string Usuario { get; set; }
        public string Actividad { get; set; }
        public string Ubicacion { get; set; }
        public string Procedimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Activo { get; set; }
    }
}
