//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.MantenimientoIdealease.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Ampr
    {
        public int Id { get; set; }
        public string TipoUnidad { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<int> Antiguedad { get; set; }
        public string NoSerie { get; set; }
        public Nullable<int> KActual { get; set; }
        public Nullable<int> KUltimoMantenimiento { get; set; }
        public string UltimoMantReal { get; set; }
        public Nullable<System.DateTime> FechaUltimoMant { get; set; }
        public string MantRealizar { get; set; }
        public string Cliente { get; set; }
        public string Negocio { get; set; }
        public string NActivoEAM { get; set; }
        public string RealizaMantenimiento { get; set; }
        public string TipoContMant { get; set; }
        public string SucursalAsig { get; set; }
        public string SucursalMant { get; set; }
        public string UbicFisUnidad { get; set; }
        public string Accion { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string CreationUser { get; set; }
        public string LastUpdateUser { get; set; }
        public string DeleteUser { get; set; }
    }
}
