//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.MantenimientoIdealease.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_Anpc
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<decimal> FkmsPMA { get; set; }
        public Nullable<int> FdiasPMA { get; set; }
        public Nullable<decimal> FkmsPMB { get; set; }
        public Nullable<int> FdiasPMB { get; set; }
        public Nullable<decimal> FkmsPMC { get; set; }
        public Nullable<int> FdiasPMC { get; set; }
        public bool Activo { get; set; }
        public string Accion { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string CreationUser { get; set; }
        public string LastUpdateUser { get; set; }
        public string DeleteUser { get; set; }
    
        public virtual TC_Ucst TC_Ucst { get; set; }
    }
}
